API/urls.py
from django.urls import path, include
from .views import *
from rest_framework.routers import DefaultRouter
from rest_framework.routers import SimpleRouter

router = DefaultRouter()

router.register('advanced/Player', AdvancedRegistration_Player_ApiView)
router.register('advanced/Agent', AdvancedRegistration_Agent_ApiView)
router.register('advanced/Trainer', AdvancedRegistration_Trainer_ApiView)
router.register('advanced/Parent', AdvancedRegistration_Parent_ApiView)
router.register('advanced/Club', AdvancedRegistration_Club_ApiView)
router.register('advanced/Scout', AdvancedRegistration_Scout_ApiView)

urlpatterns = [
    path('', include(router.urls)),
    # path('all/', MultiModelAPIView.as_view()),
    path('add/photo/', UserPhotoApiView.as_view({'get': 'list'}), name='user-photo-list'),
    path('add/photo/<str:username>/',
         UserPhotoApiView.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy', 'post': 'create'}),
         name='user-photo'),
    path('add/video/', AdvancedRegistration_Video_ApiView.as_view({'get': 'list'}), name='user-video-list'),
    path('add/video/<str:username>/',
         AdvancedRegistration_Video_ApiView.as_view(
             {'get': 'retrieve', 'post': 'create', 'delete': 'destroy'}),
         name='user-video'),
    path('add/video/<str:username>/<int:pk>/',
         AdvancedRegistration_Video_ApiView.as_view(
             {'delete': 'destroy'}),
         name='user-video'),
    path('advanced/Player/<str:username>/',
         AdvancedRegistration_Player_ApiView.as_view({'put': 'update_username', 'delete': 'destroy'}),
         name='player-detail'),
    path('advanced/Agent/<str:username>/',
         AdvancedRegistration_Agent_ApiView.as_view({'put': 'update_username', 'delete': 'destroy'}),
         name='agent-detail'),
    path('advanced/Parent/<str:username>/',
         AdvancedRegistration_Parent_ApiView.as_view({'put': 'update_username', 'delete': 'destroy'}),
         name='parent-detail'),
    path('advanced/Club/<str:username>/',
         AdvancedRegistration_Club_ApiView.as_view({'put': 'update_username', 'delete': 'destroy'}),
         name='club-detail'),
    path('advanced/Scout/<str:username>/',
         AdvancedRegistration_Scout_ApiView.as_view({'put': 'update_username', 'delete': 'destroy'}),
         name='scout-detail'),
    path('advanced/Trainer/<str:username>/',
         AdvancedRegistration_Trainer_ApiView.as_view({'put': 'update_username', 'delete': 'destroy'}),
         name='trainer-detail')
]

CV_Sport/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from API.views import RegisterView, UserDeleteView


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('api/', include('API.urls')),
                  path('chat/', include('chat.urls')),
                  path('registration/',RegisterView.as_view(), name='registration'),
                  path('unregister/<str:username>/delete/',UserDeleteView.as_view(), name='delete_user'),
                  path('login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
                  path('login/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
                  path('login/verify/', TokenVerifyView.as_view(), name='token_verify'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

API/models.py
# from django.contrib.auth.models import User, AbstractUser
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import pre_delete, pre_save
from django.dispatch import receiver
import os
from django.conf import settings
from django.utils import timezone
# from registration.models import UserData
from multiselectfield import MultiSelectField

POSITION_CHOICES = (
    ('goalkeeper', 'Вратарь'),
    ('central_defender', 'Центральный защитник'),
    ('left_defender', 'Левый защитник'),
    ('right_defender', 'Правый защитник'),
    ('central_defensive_midfielder', 'Центральный опорный полузащитник'),
    ('central_midfielder', 'Центральный полузащитник'),
    ('left_midfielder', 'Левый полузащитник'),
    ('right_midfielder', 'Правый полузащитник'),
    ('centre forward', 'Центральный нападающий'),
    ('right_winger', 'Правый вингер'),
    ('left_winger', 'Левый вингер'),
    ('insider', 'Инсайдер'),
)


# class User(AbstractBaseUser):
#     email = models.EmailField(max_length=255, unique=True)
#     username = models.CharField(max_length=30, unique=True)
#     role = models.CharField(max_length=30)
#
#     USERNAME_FIELD = 'email'
#     REQUIRED_FIELDS = ['username']
#
#     def __str__(self):
#         return self.email

def photo_upload_to(instance, filename):
    return 'data/{}/photo/{}'.format(instance.user.username, filename)


def video_upload_to(instance, filename):
    return 'data/{}/video/{}'.format(instance.user.username, filename)


class View(models.Model):
    ip_address = models.CharField(max_length=45, blank=True, null=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    created_at = models.DateTimeField(auto_now_add=True)


class User(AbstractUser):
    role = [
        ('Player', 'Игрок'),
        ('Agent', 'Агент'),
        ('Club', 'Клуб'),
        ('Parent', 'Родитель'),
        ('Trainer', 'Тренер'),
        ('Scout', 'Скаут'),
    ]
    username = models.CharField(max_length=150, unique=True)
    role = models.CharField(verbose_name='Роль', max_length=20, choices=role, blank=True, null=True,
                                 default='player')


class UserPhoto(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, to_field='username')
    photo = models.ImageField(upload_to=photo_upload_to, blank=True)

    def get_user_role(self):
        return self.user.role


@receiver(pre_delete, sender=UserPhoto)
def userphoto_delete(sender, instance, **kwargs):
    # Удаляем файл при удалении объекта UserPhoto
    if instance.photo:
        if os.path.isfile(instance.photo.path):
            os.remove(instance.photo.path)


class Player(models.Model):
    leg = [
        ('R', 'Правая'),
        ('L', 'Левая'),
        ('B', 'Обе')
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, to_field='username', blank=True, null=True)
    leg = models.TextField('Нога', choices=leg, blank=True, null=True)
    position = MultiSelectField(verbose_name='Позиция', choices=POSITION_CHOICES, blank=True, null=True)
    age = models.CharField("Возраст", max_length=5, blank=True, null=True)
    first_name = models.CharField("Имя", max_length=30, blank=True, null=True)
    second_name = models.CharField("Фамилия", max_length=30, blank=True, null=True)
    patronymic = models.CharField("Отчество", max_length=30, blank=True, null=True)
    height = models.CharField("Рост", max_length=4, blank=True, null=True)
    weight = models.CharField("Вес", max_length=4, blank=True, null=True)
    phone = models.CharField("Номер Телефона", max_length=30, blank=True, null=True)
    email = models.EmailField("Почта", max_length=100, blank=True, null=True)
    country = models.CharField("Страна", max_length=40, blank=True, null=True)
    shengen = models.BooleanField("Шенген", default=False, blank=True, null=True)
    city = models.CharField("Город", max_length=40, blank=True, null=True)
    description = models.TextField("Описание", max_length=254, blank=True, null=True)
    is_show = models.BooleanField("Отображать_всем", default=True, blank=True, null=True)
    views = models.ManyToManyField(View, related_name="player_views", blank=True)
    subscribe = models.IntegerField("Количество видео", blank=True, default=1)

    # photo = models.ImageField("Фото в профиле", upload_to="profile_photoes", null=True, blank=True)

    def __str__(self):
        return str(self.user)

    def total_views(self):
        return self.views.count()


class PlayersVideo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, to_field='username', blank=True, null=True)
    player = models.ForeignKey(Player, on_delete=models.CASCADE, blank=True, null=True)
    video = models.FileField("Видео", upload_to=video_upload_to, null=True, blank=True, max_length=150)
    description = models.TextField(blank=True, null=True, )
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField("Заголовок", max_length=255, blank=True)

    def __str__(self):
        return str(self.video.name)


@receiver(pre_delete, sender=PlayersVideo)
def userphoto_delete(sender, instance, **kwargs):
    # Удаляем файл при удалении объекта UserPhoto
    if instance.video:
        if os.path.isfile(instance.video.path):
            os.remove(instance.video.path)


class Agent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField("Имя", max_length=20, blank=True, null=True)
    second_name = models.CharField("Фамилия", max_length=30, blank=True, null=True)
    patronymic = models.CharField("Отчество", max_length=30, blank=True, null=True)
    phone = models.CharField("Номер Телефона", max_length=30, blank=True, null=True)
    email = models.EmailField("Почта", max_length=100, blank=True, null=True)
    country = models.CharField("Страна", max_length=40, blank=True, null=True)
    city = models.CharField("Город", max_length=40, blank=True, null=True)
    is_show = models.BooleanField("Отображать_всем", default=True, blank=True, null=True)
    # photo = models.ImageField("Фото в профиле", upload_to="profile_photoes", null=True, blank=True)
    players = models.ManyToManyField(Player, related_name="agent_players", blank=True, verbose_name="Игроки агента")

    def __str__(self):
        return str(f"{self.first_name} {self.second_name} {self.patronymic}")


class Parent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField("Имя", max_length=20, blank=True, null=True)
    second_name = models.CharField("Фамилия", max_length=30, blank=True, null=True)
    patronymic = models.CharField("Отчество", max_length=30, blank=True, null=True)
    phone = models.CharField("Номер Телефона", max_length=30, blank=True, null=True)
    email = models.EmailField("Почта", max_length=100, blank=True, null=True)
    country = models.CharField("Страна", max_length=40, blank=True, null=True)
    city = models.CharField("Город", max_length=40, blank=True, null=True)
    is_show = models.BooleanField("Отображать_всем", default=True, blank=True, null=True)
    # passport = models.ImageField("Фото паспорта", upload_to='documents/', blank=True)
    players = models.ManyToManyField(Player, related_name="parent_players", blank=True, verbose_name="Игроки родителя")
    views = models.ManyToManyField(View, related_name='players', verbose_name='Просмотры', blank=True)

    # photo = models.ImageField("Фото в профиле", upload_to="profile_photoes", null=True, blank=True)

    def __str__(self):
        return str(f"{self.first_name} {self.second_name} {self.patronymic}")


class Trainer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField("Имя", max_length=20, blank=True, null=True)
    second_name = models.CharField("Фамилия", max_length=30, blank=True, null=True)
    patronymic = models.CharField("Отчество", max_length=30, blank=True, null=True)
    phone = models.CharField("Номер Телефона", max_length=30, blank=True, null=True)
    email = models.EmailField("Почта", max_length=100, blank=True, null=True)
    country = models.CharField("Страна", max_length=40, blank=True, null=True)
    is_show = models.BooleanField("Отображать_всем", default=True, blank=True, null=True)
    city = models.CharField("Город", max_length=40, blank=True, null=True)
    # passport = models.ImageField("Фото паспорта", upload_to='documents/', blank=True)

    players = models.ManyToManyField(Player, related_name="trainer_players", blank=True, verbose_name="Игроки тренера")
    # photo = models.ImageField("Фото в профиле", upload_to="profile_photoes", null=True, blank=True)
    # school description (ending 's' does meen 'school')

    country_s = models.CharField("Страна, в которой находится школа", max_length=50, blank=True)
    city_s = models.CharField("Город, в котором находится школа", max_length=50, blank=True)
    phone_s = models.CharField("Номер телефона школы", max_length=15, blank=True)
    e_mail_s = models.EmailField("E-Mail школы", blank=True)
    photo_s = models.FileField("Фото школы", upload_to="school_photoes", null=True, blank=True)

    # телефон, e-mail, фото до 10, ссылки на ютуб, и т.п. до 10

    def __str__(self):
        return str(f"{self.first_name} {self.second_name} {self.patronymic}")


class Club(models.Model):
    ages = [
        ('3-4', '3-4'),
        ('5-6', '5-6'),
        ('7-8', '7-8'),
        ('9-10', '9-10'),
        ('11-12', '11-12'),
        ('13-14', '13-14'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

templates/profile/main.html
<!DOCTYPE html>

{% load static %}

<html>
    <head id="head">
    <title>Главная</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link href="https://vjs.zencdn.net/7.20.3/video-js.css" rel="stylesheet" />
    </head>
    <body>
    <div>
        {% for video in videos %}
        <div class="video_one">
            <a class="video" href="profile/{{video.user.user.role}}/{{video.user.user.user}}">
            <video
                id="v0"
                class="video-js"
                poster="{{ video.image.url }}">
                    <source src="{{ video.file.url }}">
                </video>
                <h4> {{ video.title }} </h4>
            </a>
        </div>
        {% endfor %}
    </div>
    </body>
    <script src="https://vjs.zencdn.net/7.20.3/video.min.js"></script>
    <script>
        const devices = new RegExp('Android|webOS|iPhone|iPad|iPod|BlackBerry|BB|PlayBook|IEMobile|Windows Phone|Kindle|Silk|Opera Mini', "i"); 
        let linkFile = document.createElement("link");
        const heade = document.getElementById('head');
          if (devices.test(navigator.userAgent)) 
          { 
              linkFile.rel = 'stylesheet';
              linkFile.href = "{% static 'css/mobile.css' %}"
          } 
          else 
          { 
              linkFile.rel = 'stylesheet';
              linkFile.href = "{% static 'css/comp.css' %}"
          } 
        heade.appendChild(linkFile);
        vid = document.getElementById('v0'); 
 
        vid.addEventListener('mouseenter', function() {
        vid.play();
        });

        vid.addEventListener('mouseleave', function() {
        vid.pause();
        });
    </script>
</html>

templates/profile/profile.html
<!DOCTYPE html>
{% load static %}

<html>
<head id="head">
    <title>Профиль {{ user }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link href="https://vjs.zencdn.net/7.20.3/video-js.css" rel="stylesheet" >
<head>
    <body>
    <div class="info_profile">
        <div class="profile_photo">
            <img src={{ profile.user.photo.url }}>
        </div>
        <div class="profile_text">
                <h2>ФИО: {{ profile.user.first_name }} {{ profile.user.second_name }} {{ profile.user.patronimyc }}</h2>
                <h3>{% if role == '1' %} Игрок на позиции {{ profile.get_position_display }} 
                    <h3>играю ногой: {{ profile.get_leg_display }}</h3>
                    <h3>Проживание: {{ profile.user.country }}, {{ profile.user.city }}</h3>
                    <h3>Возраст: {{ profile.user.age }}</h3>
                    <h3>Рост: {{ profile.user.height }} см.</h3>
                    <h3>Вес: {{ profile.user.weight }} кг.</h3>
                    <h3>Телефон: {{ profile.user.phone }}</h3>
                    <h3>Почта: {{ profile.user.email }}</h3>
                    <h3>{% if profile.user.shengen %}Есть шенген{% else %}Без шенгена{% endif %}</h3>
                    <h3>{{ profile.user.sources }}</h3>
                    <div class="container"> 
                    {% for video in videos %}
                    <a href="{{ video.file.url }}">
                        <center>
                            <video
                                id="v0"
                                controls
                                class="video-js"
                                poster="{{ video.image.url }}" >
                                <source src="{{ video.file.url }}">
                            </video>
                        </center>
                    </a>
                        <center>
                            <video
                                id="v0"
                                controls
                                class="video-js"
                                poster="{{ video.image.url }}" >
                                <source src="{{ video.file.url }}">
                            </video>
                        </center>
                    {% endfor %}
                    {% elif role == '2' %}Роль: Агент 
                    <h3>Описание: {{ profile.user.description }}</h3>
                    <h3>Проживание: {{ profile.user.country }}, {{ profile.user.city }}</h3>
                    <h3>Номер телефона: {{ profile.user.phone }}</h3>
                    <h3>E-mail: {{ profile.user.email }}</h3>
                    <form method="post">
                        {% csrf_token %}
                        <label>
                            <i>Добавить игрока</i>
                            <input type="text" name="player_data">Фамилия 
                            <input type="text" name="player_data">Имя 
                            <input type="text" name="player_data">Отчество
                            <button formmethod="post">+</button>
                        </label>
                    </form>
                    {% elif role == '3' %}Роль: Тренер
                    <h3>Описание: {{ profile.user.description }}</h3>
                    <h3>Проживание: {{ profile.user.country }}, {{ profile.user.city }}</h3>
                    <h3>Номер телефона: {{ profile.user.phone }}</h3>
                    <h3>E-mail: {{ profile.user.email }}</h3>
                    <h3>Адрес школы, в которой обучает: {{ profile.country_s }}, {{ profile.city_s }}</h3>
                    <h3>Номер школы: {{ profile.phone_s }}</h3>
                    <h3>E-mail школы {{ profile.e_mail_s }}</h3>
                    
                    {% elif role == '4' %}Роль: Родитель
                    <h3>Описание: {{ profile.user.description }}</h3>
                    <h3>Проживание: {{ profile.user.country }}, {{ profile.user.city }}</h3>
                    <h3>Номер телефона: {{ profile.user.phone }}</h3>
                    <h3>E-mail: {{ profile.user.email }}</h3>
                    {% elif role == '5' %}Роль: Клуб
                    <h3>Описание: {{ profile.user.description }}</h3>
                    <h3>Проживание: {{ profile.user.country }}, {{ profile.user.city }}</h3>
                    <h3>Номер телефона: {{ profile.user.phone }}</h3>
                    <h3>E-mail: {{ profile.user.email }}</h3>
                    {% elif role == '6' %}Роль: Скаут
                    <h3>Описание: {{ profile.user.description }}</h3>
                    <h3>Проживание: {{ profile.user.country }}, {{ profile.user.city }}</h3>
                    <h3>Номер телефона: {{ profile.user.phone }}</h3>
                    <h3>E-mail: {{ profile.user.email }}</h3>
                {% endif %}</h3>
        </div>
    </div>
    </body>
    <script src="https://vjs.zencdn.net/7.20.3/video.min.js"></script>
    <script>
        const devices = new RegExp('Android|webOS|iPhone|iPad|iPod|BlackBerry|BB|PlayBook|IEMobile|Windows Phone|Kindle|Silk|Opera Mini', "i"); 
        let linkFile = document.createElement("link");
        const heade = document.getElementById('head');
          if (devices.test(navigator.userAgent)) 
          { 
              linkFile.rel = 'stylesheet';
              linkFile.href = "{% static 'css/mobile.css' %}"
          } 
          else 
          { 
              linkFile.rel = 'stylesheet';
              linkFile.href = "{% static 'css/comp.css' %}"
          } 
        heade.appendChild(linkFile);
        vid = document.getElementById('v0'); 
 
        vid.addEventListener('mouseenter', function() {
        vid.play();
        });

        vid.addEventListener('mouseleave', function() {
        vid.pause();
        });
    </script>
</html>